import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'

const frontendRoot = path.resolve(import.meta.dirname, '..', '..', 'frontend')

test('frontend keeps Markdown/A4 in the workbench and Agent as a full-height peer', async () => {
  const source = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'main.tsx'), 'utf8')
  const css = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'styles.css'), 'utf8')
  assert.match(source, /<div className="route-content" id="routeContent" \/>[\s\S]*?id="assistantDrawer"/)
  assert.match(css, /\.app-shell\.assistant-open \{ grid-template-columns:var\(--sidebar-width\) 1px minmax\(0,1fr\) 1px var\(--assistant-width\); \}/)
  assert.match(css, /\.app-shell\.assistant-open \.assistant-drawer \{ position:static; grid-column:5; grid-row:1; width:auto; height:100%;/)
  assert.match(css, /\.app-shell\.assistant-open \.resize-assistant \{ grid-column:4; grid-row:1; display:block; \}/)
  assert.match(css, /\.app-shell \{ border:1px solid #e2e5e9; border-radius:10px;/)
  assert.match(css, /\.editor-pane \{ border-right:1px solid var\(--workbench-seam\); background:#fff; \}/)
  assert.match(css, /\.editor-pane \.editor-layout \{ padding:0 0 10px; \}/)
  assert.match(css, /\.editor-layout textarea \{ margin:0; padding:16px; border:0; border-radius:0;/)
  assert.match(css, /\.editor-foot \{ padding:8px 16px 0; border-top:1px solid var\(--workbench-weak\); \}/)
  assert.match(css, /\.direct-preview-stage \{ padding:8px; background:var\(--canvas\); \}/)
  assert.match(css, /\.direct-preview-foot \{ padding:8px 16px; border-top-color:var\(--workbench-weak\); \}/)
  assert.match(css, /@media \(min-width:901px\) \{[\s\S]*?\.app-shell:not\(\.assistant-open\) \.route-view \{ padding:0; \}[\s\S]*?\.app-shell:not\(\.assistant-open\) \.workbench-view \{ padding:0; \}[\s\S]*?\.app-shell:not\(\.assistant-open\) \.workbench-split \{ height:calc\(100dvh - var\(--shell-header-height\)\); \}/)
  assert.match(css, /@media \(min-width:901px\) \{[\s\S]*?\.app-shell\.assistant-open \.workbench-split \{ height:calc\(100dvh - var\(--shell-header-height\)\); \}/)
  assert.match(css, /\.resize-handle \{[\s\S]*?width:1px; min-width:1px;/)
  assert.match(css, /\.resize-handle::before \{[\s\S]*?left:0; width:1px;[\s\S]*?opacity:1;/)
  assert.match(css, /\.resize-handle::after \{[\s\S]*?left:-4px; width:9px;/)
  assert.match(css, /\.assistant-drawer \.drawer-header \{[\s\S]*?display:flex;[\s\S]*?border-bottom:1px solid #e8eaed;/)
  assert.match(css, /\.assistant-drawer \.assistant-context \{ display:none; \}/)
  assert.match(css, /\.assistant-drawer #assistantContent \{ height:calc\(100% - var\(--shell-header-height\)\); \}/)
})

test('frontend moves the full-height Agent below the workbench on narrow screens', async () => {
  const css = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'styles.css'), 'utf8')
  assert.match(css, /\.app-shell\.assistant-open \.main-stage \{ grid-column:3; grid-row:1; height:auto; min-height:100vh; \}/)
  assert.match(css, /\.app-shell\.assistant-open \.assistant-drawer \{ grid-column:1 \/ -1; grid-row:2; width:auto; height:min\(680px,70dvh\);/)
  assert.match(css, /\.app-shell\.assistant-open \.resize-assistant \{ display:none; \}/)
})

test('frontend keeps three columns for desktop-sized 961-1100px viewports', async () => {
  const css = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'styles.css'), 'utf8')
  assert.match(css, /@media \(min-width:961px\) and \(max-width:1100px\) \{[\s\S]*?grid-template-columns:var\(--sidebar-width\) 1px minmax\(0,1fr\) 1px minmax\(280px,min\(var\(--assistant-width\),32vw\)\);/)
  assert.match(css, /@media \(min-width:961px\) \{[\s\S]*?\.app-shell\.assistant-open \.workbench-split \{ display:grid; width:100%; min-width:0; grid-template-columns:minmax\(280px,var\(--editor-width,1fr\)\) 1px minmax\(280px,1fr\); \}/)
  assert.match(css, /\.app-shell\.assistant-open \.direct-preview-pane \{ grid-column:auto; grid-row:auto; \}/)
  assert.match(css, /@media \(min-width:961px\) and \(max-width:1100px\) \{[\s\S]*?\.app-shell\.assistant-open \.workbench-split \{ grid-template-columns:minmax\(0,1fr\) 1px minmax\(0,1fr\); \}/)
  assert.match(css, /\.app-shell\.assistant-open \.workbench-split \{ width:100%; height:calc\(100dvh - 122px\); grid-template-columns:minmax\(0,var\(--editor-width,1fr\)\) 1px minmax\(0,1fr\); \}/)
})

test('frontend keeps the measured A4 fit when Agent is open on desktop widths', async () => {
  const css = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'styles.css'), 'utf8')
  const app = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'runtime', 'workbench-runtime.js'), 'utf8')
  assert.match(css, /@media \(min-width:961px\) \{[\s\S]*?\.app-shell\.assistant-open \.workbench-split \{ display:grid; width:100%; min-width:0; grid-template-columns:minmax\(280px,var\(--editor-width,1fr\)\) 1px minmax\(280px,1fr\); \}/)
  assert.match(css, /\.app-shell\.assistant-open \.direct-preview-frame-wrap,[\s\S]*?width:var\(--preview-width,429px\); height:var\(--preview-height,607px\); transform:none;/)
  assert.match(css, /\.app-shell\.assistant-open \.direct-preview-frame-wrap iframe,[\s\S]*?transform:scale\(var\(--preview-scale,.54\)\);/)
  assert.match(app, /const WORKBENCH_MIN_PANE_WIDTH = 280/)
  assert.match(app, /const WORKBENCH_SCROLLBAR_RESERVE = 10/)
  assert.match(app, /function normalizeDesktopLayoutPrefs\(\)/)
  assert.match(app, /normalizeDesktopLayoutPrefs\(\)[\s\S]*?applyLayoutPrefs\(\)/)
  assert.match(app, /let previewFitFrame = 0/)
  assert.match(app, /function schedulePreviewFit\(\) \{[\s\S]*?window\.requestAnimationFrame\([\s\S]*?fitPreviewFrames\(\)/)
  assert.match(app, /new ResizeObserver\(\(\) => schedulePreviewFit\(\)\)/)
  assert.match(app, /frame\.style\.getPropertyValue\(name\) !== value/)
  assert.match(app, /function syncPreviewDocumentHeight\(frame\)/)
  assert.match(app, /frame\.dataset\.documentHeight/)
  assert.match(app, /frameWrap\.dataset\.pageCount/)
  assert.match(app, /payload\.event === 'render_succeeded'[\s\S]*?liveState\.renderId = payload\.renderId[\s\S]*?syncPreviewFrames\(\)/)
})

test('frontend route changes reset scroll and SSE proxy tolerates client disconnects', async () => {
  const app = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'runtime', 'workbench-runtime.js'), 'utf8')
  const proxy = await fs.readFile(path.join(frontendRoot, 'server.mjs'), 'utf8')
  assert.match(app, /function renderRoute\(route\) \{[\s\S]*?\$\('#routeView'\)\.scrollTop = 0/)
  assert.match(app, /async function renderTemplates\(\) \{[\s\S]*?const viewport = \$\('#routeView'\)[\s\S]*?viewport\.scrollTop = 0/)
  assert.match(proxy, /if \(response\.headersSent \|\| response\.destroyed \|\| response\.writableEnded \|\| request\.aborted\)/)
  assert.match(proxy, /proxyLog\('info', 'api_proxy_client_closed'/)
})

test('Agent chat keeps one state reducer for streaming, replay, and failed-run recovery', async () => {
  const app = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'runtime', 'workbench-runtime.js'), 'utf8')
  const chat = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'runtime', 'agent-chat.js'), 'utf8')
  const state = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'runtime', 'agent-chat-state.js'), 'utf8')
  const server = await fs.readFile(path.join(frontendRoot, '..', 'backend', 'src', 'server.js'), 'utf8')
  assert.match(app, /isSameAgentRun\(payload, liveState\.agentRunId\)/)
  assert.match(app, /syncActiveSessionFromServer\(\{ preserveLiveTurn: failed \}\)/)
  assert.match(app, /reportClientEvent\?\.\('agent_sse_error'/)
  assert.match(chat, /runEventStatus\(group\.events\)/)
  assert.match(state, /export function mergeSessionMessages/)
  assert.match(server, /const replay = Array\.isArray\(session\.workflowEvents\)/)
  assert.match(server, /agent_sse_connected/)
})

test('React/Vite shell owns the DOM contract and bundled runtime boundary', async () => {
  const reactRoot = path.join(frontendRoot, 'react')
  const packageJson = JSON.parse(await fs.readFile(path.join(reactRoot, 'package.json'), 'utf8'))
  const source = await fs.readFile(path.join(reactRoot, 'src', 'main.tsx'), 'utf8')
  const viteConfig = await fs.readFile(path.join(reactRoot, 'vite.config.ts'), 'utf8')
  const proxy = await fs.readFile(path.join(frontendRoot, 'server.mjs'), 'utf8')
  assert.equal(packageJson.scripts.build, 'tsc --noEmit && vite build')
  assert.equal(packageJson.scripts.typecheck, 'tsc --noEmit')
  assert.match(source, /id="appShell"/)
  assert.match(source, /id="routeContent"/)
  assert.match(source, /id="assistantDrawer"/)
  assert.match(source, /mountMarkdownPane/)
  assert.match(source, /mountA4Pane/)
  assert.match(source, /className="workbench|className="resize-handle resize-sidebar"/)
  assert.match(source, /await import\('\.\/runtime\/api-client\.js'\)/)
  assert.match(source, /await import\('\.\/runtime\/client-events\.js'\)/)
  assert.match(source, /await import\('\.\/runtime\/agent-chat\.js'\)/)
  assert.match(source, /await import\('\.\/runtime\/workbench-runtime\.js'\)/)
  assert.match(viteConfig, /base: '\/react\/'/)
  assert.match(proxy, /const reactDist = join\(root, 'react', 'dist'\)/)
  assert.match(proxy, /const reactRequest = url\.pathname\.startsWith\('\/react\/'\)/)
  assert.match(proxy, /if \(url\.pathname === '\/'\) \{[\s\S]*?location: '\/react\/'/)
  assert.match(proxy, /const publicRoot = reactDist/)
  assert.match(source, /function loadRuntimeModules\(\)/)
})

test('React shell uses one shared header geometry contract across brand, route, panes, and Agent', async () => {
  const reactRoot = path.join(frontendRoot, 'react', 'src')
  const source = await fs.readFile(path.join(reactRoot, 'main.tsx'), 'utf8')
  const header = await fs.readFile(path.join(reactRoot, 'components', 'PaneHeader.tsx'), 'utf8')
  const css = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'styles.css'), 'utf8')
  assert.match(source, /<PaneHeader[\s\S]*?variant="brand"[\s\S]*?title="CVAgent"/)
  assert.match(source, /<PaneHeader variant="workspace"[\s\S]*?id="workspaceSwitcher"/)
  assert.match(source, /className="sidebar-toggle-icon"[\s\S]*?<rect x="3" y="3" width="18" height="18" rx="4" \/>[\s\S]*?<path d="M9 3v18"/)
  assert.match(source, /<PaneHeader[\s\S]*?variant="route"/)
  assert.match(source, /<PaneHeader variant="agent"/)
  assert.match(header, /variant\?: 'editor' \| 'preview' \| 'agent' \| 'route' \| 'brand' \| 'workspace'/)
  assert.match(header, /variant === 'brand' \? 'brand-lockup'/)
  assert.match(css, /--shell-header-height:58px;[\s\S]*?--pane-header-height:58px;[\s\S]*?--pane-inline-padding:16px;/)
  assert.match(css, /--shell-title-size:20px;[\s\S]*?--shell-title-line-height:25px;[\s\S]*?--pane-title-size:14px;[\s\S]*?--pane-title-line-height:20px;/)
  assert.match(css, /\.sidebar > \.brand-lockup \{[\s\S]*?height:var\(--shell-header-height\);[\s\S]*?padding:12px var\(--pane-inline-padding\) 10px;/)
  assert.match(css, /\.sidebar > \.brand-lockup \.pane-header-copy > b,[\s\S]*?\.main-stage > \.route-header \.route-title-line > h1,[\s\S]*?\.assistant-drawer > \.drawer-header \.pane-header-copy > b \{[\s\S]*?font-size:var\(--shell-title-size\);/)
  assert.match(css, /\.sidebar > \.workspace-switcher \.workspace-copy b,[\s\S]*?\.editor-head \.pane-header-copy > b,[\s\S]*?\.direct-preview-head \.pane-header-copy > b \{[\s\S]*?font-size:var\(--pane-title-size\);/)
  assert.match(css, /\.direct-preview-head \.preview-actions \.?button \{ box-sizing:border-box; width:auto; min-width:74px; height:32px; padding:0 10px; border:1px solid var\(--line\); border-radius:4px; color:var\(--muted\); background:#fff; white-space:nowrap; \}/)
  assert.match(css, /\.main-stage > \.route-header,[\s\S]*?\.assistant-drawer > \.drawer-header \{[\s\S]*?height:var\(--shell-header-height\);/)
  assert.match(css, /\.editor-head,.direct-preview-head \{[\s\S]*?height:var\(--pane-header-height\);[\s\S]*?padding:12px var\(--pane-inline-padding\) 10px;/)
  assert.match(css, /\.app-shell\.assistant-open \.assistant-drawer \{ padding:0; \}/)
  assert.match(css, /\.sidebar-collapsed \.sidebar > \.brand-lockup \{[\s\S]*?width:0;[\s\S]*?height:0;[\s\S]*?overflow:visible;/)
  assert.match(css, /\.sidebar-collapsed \.sidebar > \.brand-lockup \.pane-header-copy \{ display:none; \}/)
  assert.match(css, /\.sidebar-toggle-icon \{[\s\S]*?display:none;[\s\S]*?width:16px;[\s\S]*?stroke-width:1\.6;/)
  assert.match(css, /\.sidebar-collapsed \.sidebar > \.brand-lockup \.sidebar-toggle-icon \{ display:block; \}/)
})

test('React A4 pane preserves the preview contract and post-mount status sync', async () => {
  const app = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'runtime', 'workbench-runtime.js'), 'utf8')
  const bridge = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'react-pane-bridge.tsx'), 'utf8')
  const pane = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'features', 'preview', 'A4Pane.tsx'), 'utf8')
  const header = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'components', 'PaneHeader.tsx'), 'utf8')
  const css = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'styles.css'), 'utf8')
  assert.match(app, /id="a4PaneMount" data-testid="a4-pane-root"/)
  assert.match(app, /mountA4Pane\(previewMount, \{[\s\S]*?onApplyTuning: \(values\) => applyPresentationTuning\(values\)/)
  assert.match(app, /syncPreviewFrames\(\)[\s\S]*?bindPreviewFit\(\)[\s\S]*?updateHeader\(\)/)
  assert.match(app, /await loadSessionsForWorkspace\(\)[\s\S]*?syncPreviewFrames\(\)[\s\S]*?bindPreviewFit\(\)[\s\S]*?updateHeader\(\)/)
  assert.match(bridge, /export function mountA4Pane\(/)
  assert.match(pane, /data-preview-status/)
  assert.match(header, /data-preview-status/)
  assert.match(pane, /data-preview-foot-status/)
  assert.match(pane, /cvagent:a4-pane-mounted/)
  assert.match(app, /window\.addEventListener\('cvagent:a4-pane-mounted',[\s\S]*?syncPreviewFrames\(\)[\s\S]*?bindPreviewFit\(\)/)
  assert.match(app, /requiresInitialIntake = blockers\.includes\('尚未完成首次信息收集'\)/)
  assert.match(app, /needs_revision' && !requiresInitialIntake/)
  assert.match(pane, /id="presentationPanel"/)
  assert.match(css, /\.direct-preview-pane > #a4PaneMount \{ display:flex;[\s\S]*?flex-direction:column; \}/)
})

test('React A4 manual tuning follows the DSH boundary: live layout and real-icon controls, not template visual tokens', async () => {
  const app = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'runtime', 'workbench-runtime.js'), 'utf8')
  const pane = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'features', 'preview', 'A4Pane.tsx'), 'utf8')
  const renderer = await fs.readFile(path.join(frontendRoot, '..', 'backend', 'src', 'migrated', 'resume-engine', 'renderer.js'), 'utf8')
  assert.match(pane, /querySelectorAll<HTMLElement>\('\.cvagent-icon'\)/)
  assert.match(pane, /cvagent-resume-layout-preview/)
  assert.match(pane, /cvagent-resume-icon-tuning/)
  assert.match(pane, /type="range"/)
  assert.match(pane, /onDraftChange/)
  assert.match(pane, /clear: nextCleared/)
  assert.match(pane, /应用到当前草稿/)
  assert.match(pane, /滑杆实时预览/)
  assert.match(app, /presentationDraft/)
  assert.match(app, /请先将手动微调应用到当前草稿并完成真实 A4 测量/)
  assert.doesNotMatch(pane, /accentColor|backgroundColor|cornerRadius|divider/)
  assert.match(renderer, /const applyLayoutPreview = \(layout = \{\}\) =>/)
  assert.match(renderer, /const layoutQuery = \{/)
  assert.match(renderer, /window\.history\.replaceState\(null, '', previewUrl\)/)
  assert.match(renderer, /if \(needsRepagination\) window\.location\.reload\(\)/)
  assert.match(renderer, /event\.data\?\.source === 'cvagent-resume-layout-preview'/)
  assert.match(renderer, /event\.data\?\.source === 'cvagent-resume-icon-tuning'/)
})

test('template library exposes the existing copy, revision, and transient-candidate lifecycle without implicit selection', async () => {
  const app = await fs.readFile(path.join(frontendRoot, 'react', 'src', 'runtime', 'workbench-runtime.js'), 'utf8')
  assert.match(app, /function templateOrigin\(template\)/)
  assert.match(app, /if \(template\.immutable\) return '内置模板'/)
  assert.match(app, /data-template-create/)
  assert.match(app, /\/api\/templates\/generate/)
  assert.match(app, /candidate \? `<div class="template-candidate"/)
  assert.match(app, /data-template-candidate-save/)
  assert.match(app, /\/api\/templates\/save',[\s\S]*?confirmedByUser: true/)
  assert.match(app, /\/api\/templates\/copy/)
  assert.match(app, /\/api\/templates\/versions\?workspaceId=/)
  assert.match(app, /\/api\/templates\/restore',[\s\S]*?confirmedByUser: true/)
  assert.match(app, /当前简历模板未被自动切换/)
})
